/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author User
 */

import java.sql.*;
import javax.swing.*;
import Controller.KaryawanController;
import Dao.KaryawanDao;
import java.awt.Color;
import Model.Karyawan;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Form_Login extends javax.swing.JFrame {

    /**
     * Creates new form Form_Login
     */
    
    Connection con;
    Statement st;
    KaryawanController controller;
    Karyawan coba;
    KaryawanDao karyawandao;
    
    public Form_Login() {
        initComponents();
        dispose();
        controller = new KaryawanController(this);
        panel_bground2.setBackground(new Color(0,204,255,204));
    }
    
    public javax.swing.JTextField getTxt_id_login(){
        return txt_id_login;
    }
    
    public javax.swing.JTextField getTxt_password_login(){
        return txt_password_login;
    }

    public JLabel getKeterangan() {
        return keterangan;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_bground2 = new javax.swing.JPanel();
        txt_id_login = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_registrasi = new javax.swing.JButton();
        txt_password_login = new javax.swing.JPasswordField();
        lbl_bground1 = new javax.swing.JLabel();
        keterangan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        panel_bground2.setBackground(new java.awt.Color(0, 204, 255));
        panel_bground2.setPreferredSize(new java.awt.Dimension(1044, 646));

        txt_id_login.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel5.setText("LOGIN");

        btn_login.setBackground(new java.awt.Color(53, 221, 80));
        btn_login.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel7.setText("Password");

        btn_registrasi.setBackground(new java.awt.Color(53, 221, 80));
        btn_registrasi.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        btn_registrasi.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrasi.setText("REGISTRASI");
        btn_registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrasiActionPerformed(evt);
            }
        });

        txt_password_login.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout panel_bground2Layout = new javax.swing.GroupLayout(panel_bground2);
        panel_bground2.setLayout(panel_bground2Layout);
        panel_bground2Layout.setHorizontalGroup(
            panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bground2Layout.createSequentialGroup()
                .addGroup(panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bground2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_bground2Layout.createSequentialGroup()
                                .addComponent(btn_registrasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                                .addComponent(btn_login))
                            .addGroup(panel_bground2Layout.createSequentialGroup()
                                .addGroup(panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bground2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(117, 117, 117))
                                    .addGroup(panel_bground2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(34, 34, 34)))
                                .addGroup(panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_id_login, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                                    .addComponent(txt_password_login)))))
                    .addGroup(panel_bground2Layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_bground2Layout.setVerticalGroup(
            panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bground2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(89, 89, 89)
                .addGroup(panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_id_login, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_password_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 234, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bground2Layout.createSequentialGroup()
                .addContainerGap(521, Short.MAX_VALUE)
                .addGroup(panel_bground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrasi)
                    .addComponent(btn_login))
                .addGap(74, 74, 74))
        );

        jPanel1.add(panel_bground2);
        panel_bground2.setBounds(120, 40, 1044, 646);

        lbl_bground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/LOGIN.jpg"))); // NOI18N
        lbl_bground1.setText("jLabel1");
        jPanel1.add(lbl_bground1);
        lbl_bground1.setBounds(0, 0, 1280, 720);

        keterangan.setText("jLabel3");
        jPanel1.add(keterangan);
        keterangan.setBounds(10, 580, 70, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1302, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrasiActionPerformed
        // TODO add your handling code here:
        if(controller.onClickBtnRegis()){    
            Form_Registrasi f = new Form_Registrasi();
            f.setVisible(true);
            f.toFront();
            dispose();
        }
    }//GEN-LAST:event_btn_registrasiActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        Karyawan k = controller.onClickBtnLogin();
        if(controller.onClickBtnLogin2()){
            Form_MenuUtama f = new Form_MenuUtama();
            f.setVisible(true);
            f.toFront();
            f.getTxt_Id().setText(k.getId_k());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(k.getNama_k());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(k.getNohp_k());
            f.getTxt_Hp().setEditable(false);
            f.getKeterangan().setText(k.getKeterangan());
            if(k.getKeterangan().equalsIgnoreCase("Owner"))
            {
                f.getBtn_laporan().setEnabled(true);
                f.getBtn_statusair().setEnabled(true);
                f.getTxt_statusair().setEnabled(true);
                f.getjLabel3().setText("Owner");
                if(getKeterangan().getText().equalsIgnoreCase("Tersedia")){
                   f.getTxt_statusair().setText("Tersedia");
                   f.getBtn_input().setEnabled(true);
               }
                else if(getKeterangan().getText().equalsIgnoreCase("Tidak Tersedia")){
                   f.getTxt_statusair().setText("Tidak Tersedia");
                   f.getBtn_input().setEnabled(false);
               }
               else{
                   f.getBtn_input().setEnabled(false);
               }
            }
            else
            {
               f.getBtn_laporan().setEnabled(false);
               f.getBtn_statusair().setEnabled(false);
               f.getTxt_statusair().setEditable(false);
               if(getKeterangan().getText().equalsIgnoreCase("Tersedia")){
                   f.getTxt_statusair().setText("Tersedia");
               }
               else{
                   f.getTxt_statusair().setText("Tidak Tersedia");
                   f.getBtn_input().setEnabled(false);
               }
            }
            dispose();
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_registrasi;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel keterangan;
    private javax.swing.JLabel lbl_bground1;
    private javax.swing.JPanel panel_bground2;
    private javax.swing.JTextField txt_id_login;
    private javax.swing.JPasswordField txt_password_login;
    // End of variables declaration//GEN-END:variables
}