/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.KaryawanController;
import javax.swing.JOptionPane;
import Model.Karyawan;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class Form_MenuUtama extends javax.swing.JFrame {


    /**
     * Creates new form Form_MenuUtama
     */
    
    KaryawanController controller;
    int a;
    public Form_MenuUtama() {
        initComponents();
        
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }
    
    public javax.swing.JTextField getTxt_Id(){
        return txt_Id;
    }
    
    public javax.swing.JTextField getTxt_Nama(){
        return txt_Nama;
    }
    
    public javax.swing.JTextField getTxt_Hp(){
        return txt_Hp;
    }
    
    public javax.swing.JTextField getTxt_statusair(){
        return txt_statusair;
    }

    public JButton getBtn_laporan() {
        return btn_laporan;
    }

    public JButton getBtn_statusair() {
        return btn_statusair;
    }

    public JLabel getKeterangan() {
        return jLabel3;
    }

    public JButton getBtn_input() {
        return btn_input;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_statusair = new javax.swing.JButton();
        txt_statusair = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_nohp = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jLabel_nama = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_caridata = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_menuutama = new javax.swing.JButton();
        btn_input = new javax.swing.JButton();
        txt_Id = new javax.swing.JTextField();
        txt_Nama = new javax.swing.JTextField();
        txt_Hp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        keterangan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btn_statusair.setBackground(new java.awt.Color(48, 179, 235));
        btn_statusair.setFont(new java.awt.Font("Roboto", 0, 26)); // NOI18N
        btn_statusair.setText("Status Air ");
        btn_statusair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statusairActionPerformed(evt);
            }
        });
        jPanel1.add(btn_statusair);
        btn_statusair.setBounds(374, 144, 270, 60);

        txt_statusair.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        txt_statusair.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_statusair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusairActionPerformed(evt);
            }
        });
        jPanel1.add(txt_statusair);
        txt_statusair.setBounds(710, 144, 240, 60);

        jPanel2.setPreferredSize(new java.awt.Dimension(1440, 115));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU UTAMA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(330, 20, 679, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1478, 115);

        jPanel3.setBackground(new java.awt.Color(48, 179, 235));
        jPanel3.setLayout(null);

        jLabel_nohp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nohp.setText("NO HP :");
        jPanel3.add(jLabel_nohp);
        jLabel_nohp.setBounds(30, 230, 101, 45);

        jLabel_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_id.setText("ID :");
        jPanel3.add(jLabel_id);
        jLabel_id.setBounds(30, 130, 101, 45);

        jLabel_nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nama.setText("NAMA :");
        jPanel3.add(jLabel_nama);
        jLabel_nama.setBounds(30, 180, 101, 45);

        btn_logout.setBackground(new java.awt.Color(227, 247, 255));
        btn_logout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel3.add(btn_logout);
        btn_logout.setBounds(80, 640, 200, 50);

        btn_caridata.setBackground(new java.awt.Color(227, 247, 255));
        btn_caridata.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_caridata.setText("CARI DATA");
        btn_caridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caridataActionPerformed(evt);
            }
        });
        jPanel3.add(btn_caridata);
        btn_caridata.setBounds(80, 400, 200, 50);

        btn_laporan.setBackground(new java.awt.Color(227, 247, 255));
        btn_laporan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_laporan.setText("LAPORAN");
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        jPanel3.add(btn_laporan);
        btn_laporan.setBounds(80, 560, 200, 50);

        btn_menuutama.setBackground(new java.awt.Color(227, 247, 255));
        btn_menuutama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_menuutama.setText("MENU UTAMA");
        btn_menuutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuutamaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_menuutama);
        btn_menuutama.setBounds(80, 320, 200, 50);

        btn_input.setBackground(new java.awt.Color(227, 247, 255));
        btn_input.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        jPanel3.add(btn_input);
        btn_input.setBounds(80, 480, 200, 50);

        txt_Id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });
        jPanel3.add(txt_Id);
        txt_Id.setBounds(160, 130, 180, 45);

        txt_Nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel3.add(txt_Nama);
        txt_Nama.setBounds(160, 180, 180, 45);

        txt_Hp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel3.add(txt_Hp);
        txt_Hp.setBounds(160, 230, 180, 45);

        jLabel3.setText("jLabel4");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(180, 250, 34, 14);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 2, 359, 1020);

        jPanel4.setMinimumSize(new java.awt.Dimension(893, 861));
        jPanel4.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GALON.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(893, 163));
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel2);
        jLabel2.setBounds(0, 0, 840, 550);

        keterangan.setText("jLabel3");
        jPanel4.add(keterangan);
        keterangan.setBounds(10, 580, 70, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(431, 163, 840, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1302, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int pesan=JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar?","",JOptionPane.YES_NO_OPTION
            ,JOptionPane.QUESTION_MESSAGE);
        if(pesan==JOptionPane.YES_OPTION){
            Form_Login l = new Form_Login();
            if(getTxt_statusair().getText().equalsIgnoreCase("Tersedia")){
                l.getKeterangan().setText("Tersedia");
            }
            else
            {
                l.getKeterangan().setText("Tidak tersedia");
            }
            l.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_caridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caridataActionPerformed
        // TODO add your handling code here:
            Form_Caridata f = new Form_Caridata();
            f.setVisible(true);
            f.toFront();
            dispose();
            //Form_Caridata f = new Form_Caridata();
            //f.setVisible(true);
            //f.toFront();
            f.getTxt_Id().setText(getTxt_Id().getText());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
            f.getjLabel3().setText(getjLabel3().getText());
            if(getjLabel3().getText().equals("Owner")){
                f.getBtn_edit().setEnabled(true);
                if(getTxt_statusair().getText().equalsIgnoreCase("Tersedia")){
                    f.getBtn_input().setEnabled(true);
                }
                else
                {
                    f.getBtn_input().setEnabled(false);
                }
                f.getBtn_laporan().setEnabled(true);
                f.getjLabel4().setText(getTxt_statusair().getText());
            }
            else{
                f.getBtn_edit().setEnabled(false);
                if(getTxt_statusair().getText().equalsIgnoreCase("Tersedia")){
                    f.getBtn_input().setEnabled(true);
                }
                else
                {
                    f.getBtn_input().setEnabled(false);
                }
                f.getBtn_laporan().setEnabled(false);
                f.getjLabel4().setText(getTxt_statusair().getText());
            }
    }//GEN-LAST:event_btn_caridataActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
            
            Form_Input f = new Form_Input();
            f.setVisible(true);
            f.toFront();
            f.getTxt_Id().setText(getTxt_Id().getText());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
            f.getjLabel6().setText(getjLabel3().getText());
            f.getjLabel7().setText(getTxt_statusair().getText());
            if(getjLabel3().getText().equals("Owner")){
                f.getBtn_laporan().setEnabled(true);
                if(getTxt_statusair().getText().equalsIgnoreCase("Tersedia")){
                    f.getBtn_input().setEnabled(true);
                }
                else
                {
                    f.getBtn_input().setEnabled(false);
                }
                f.getBtn_laporan().setEnabled(true);
                f.getjLabel6().setText(getTxt_statusair().getText());
            }
            else{
                f.getBtn_laporan().setEnabled(false);
                if(getTxt_statusair().getText().equalsIgnoreCase("Tersedia")){
                    f.getBtn_input().setEnabled(true);
                }
                else
                {
                    f.getBtn_input().setEnabled(false);
                }
                f.getBtn_laporan().setEnabled(false);
                f.getjLabel7().setText(getTxt_statusair().getText());
            }
            dispose();
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
       // new Form_Laporan().show();
        Form_Laporan l = new Form_Laporan();
        l.setVisible(true);
        l.toFront();
        l.getjLabel4().setText(getjLabel3().getText());
        l.getTxt_Nama().setText(getTxt_Nama().getText());
        l.getTxt_Id().setText(getTxt_Id().getText());
        l.getTxt_Hp().setText(getTxt_Hp().getText());
        l.getjLabel2().setText(getTxt_statusair().getText());
        dispose();
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void txt_statusairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusairActionPerformed

    private void btn_statusairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statusairActionPerformed
        // TODO add your handling code here:
        int pesan=JOptionPane.showConfirmDialog(null, "Air Tersedia?","",JOptionPane.YES_NO_OPTION
            ,JOptionPane.QUESTION_MESSAGE);
        if(pesan==JOptionPane.YES_OPTION){
            a=0;
            getTxt_statusair().setText("Tersedia");
            btn_input.setEnabled(true);
            getTxt_statusair().setEditable(false);
        }
        else if (pesan==JOptionPane.NO_OPTION)
        {
            a=1;
            getTxt_statusair().setText("Tidak Tersedia");
            btn_input.setEnabled(false);
            getTxt_statusair().setEditable(false);
        }
    }//GEN-LAST:event_btn_statusairActionPerformed

    private void btn_menuutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuutamaActionPerformed
        // TODO add your handling code here:
//            Form_MenuUtama f = new Form_MenuUtama();
//            f.setVisible(true);
//            f.toFront();
//            f.getTxt_Id().setText(getTxt_Id().getText());
//            f.getTxt_Id().setEditable(false);
//            f.getTxt_Nama().setText(getTxt_Nama().getText());
//            f.getTxt_Nama().setEditable(false);
//            f.getTxt_Hp().setText(getTxt_Hp().getText());
//            f.getTxt_Hp().setEditable(false);
//            f.getjLabel3().setText(getjLabel3().getText());
//            f.getTxt_statusair().setText(getTxt_statusair().getText());
//            if(getTxt_statusair().getText().equalsIgnoreCase("Tersedia")){
//                f.getBtn_input().setEnabled(true);
//            }
//            else
//            {
//                f.getBtn_input().setEnabled(false);
//            }
//            dispose();
    }//GEN-LAST:event_btn_menuutamaActionPerformed

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caridata;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_menuutama;
    private javax.swing.JButton btn_statusair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_nama;
    private javax.swing.JLabel jLabel_nohp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel keterangan;
    private javax.swing.JTextField txt_Hp;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextField txt_statusair;
    // End of variables declaration//GEN-END:variables
}
