/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.KaryawanController;
import Controller.MemesanController;
import java.awt.Color;
import javax.swing.JOptionPane;
import Model.Karyawan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class Form_Input extends javax.swing.JFrame {


    /**
     * Creates new form Form_MenuUtama
     */
    KaryawanController controller;
    MemesanController controllerM;
    Connection con;
    Statement stat;
    ResultSet rs;
    public Form_Input() {
        initComponents();
        dispose();
        controllerM = new MemesanController(this);
        txt_total.setEnabled(false);
        txt_biaya.setEnabled(false);
        panel_bground2.setBackground(new Color(27,22,22,127));
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JComboBox<String> getCbo_voucher() {
        return cbo_voucher;
    }
    
    public javax.swing.JTextField getTxt_idpelanggan(){
        return txt_idpelanggan;
    }
    
    public javax.swing.JTextField getTxt_namapelanggan(){
        return txt_namapelanggan;
    }
    
    public javax.swing.JTextField getTxt_alamat(){
        return txt_alamat;
    }
    
    public javax.swing.JTextField getTxt_nohppelanggan(){
        return txt_nohppelanggan;  
    }
    
    public javax.swing.JTextField getTxt_pesanan(){
        return txt_pesanan;
    }
    
    public javax.swing.JTextField getTxt_biaya(){
        return txt_biaya;
    }
    
    public javax.swing.JTextField getTxt_namagalonman(){
        return txt_namagalonman;
    }
    
    public JComboBox<String> getCbo_idgalonman() {
        return cbo_idgalonman;
    }
    
    public javax.swing.JTextField getTxt_Id(){
        return txt_Id;
    }
    
    public javax.swing.JTextField getTxt_Nama(){
        return txt_Nama;
    }
    
    public javax.swing.JTextField getTxt_Hp(){
        return txt_Hp;
    }

    public JTextField getTxt_diskon() {
        return txt_diskon;
    }

    public JTextField getTxt_total() {
        return txt_total;
    }

    public JButton getBtn_caridata() {
        return btn_caridata;
    }

    public JButton getBtn_input() {
        return btn_input;
    }

    public JButton getBtn_laporan() {
        return btn_laporan;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        jLabel_nohp = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jLabel_nama = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_caridata = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_menuutama = new javax.swing.JButton();
        btn_input = new javax.swing.JButton();
        txt_Id = new javax.swing.JTextField();
        txt_Nama = new javax.swing.JTextField();
        txt_Hp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel_bground2 = new javax.swing.JPanel();
        jLabel_namagalonman = new javax.swing.JLabel();
        txt_namagalonman = new javax.swing.JTextField();
        txt_namapelanggan = new javax.swing.JTextField();
        jLabel_namapelanggan = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jLabel_alamat = new javax.swing.JLabel();
        txt_nohppelanggan = new javax.swing.JTextField();
        jLabel_nohppelanggan = new javax.swing.JLabel();
        txt_pesanan = new javax.swing.JTextField();
        jLabel_pesanan = new javax.swing.JLabel();
        jLabel_biaya = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        cbo_idgalonman = new javax.swing.JComboBox<>();
        jLabel_idgalonman = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbo_voucher = new javax.swing.JComboBox<>();
        btn_batalkan = new javax.swing.JButton();
        btn_kirim = new javax.swing.JButton();
        jLabel_idpelanggan = new javax.swing.JLabel();
        txt_idpelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JTextField();
        txt_biaya = new javax.swing.JTextField();
        panel_galon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        panel_judul.setPreferredSize(new java.awt.Dimension(1440, 115));
        panel_judul.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INPUT");
        panel_judul.add(jLabel1);
        jLabel1.setBounds(300, 30, 679, 60);

        jPanel1.add(panel_judul);
        panel_judul.setBounds(0, 0, 1478, 115);

        panel_menu.setBackground(new java.awt.Color(48, 179, 235));
        panel_menu.setLayout(null);

        jLabel_nohp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nohp.setText("NO HP :");
        panel_menu.add(jLabel_nohp);
        jLabel_nohp.setBounds(30, 230, 101, 45);

        jLabel_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_id.setText("ID :");
        panel_menu.add(jLabel_id);
        jLabel_id.setBounds(30, 130, 101, 45);

        jLabel_nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nama.setText("NAMA :");
        panel_menu.add(jLabel_nama);
        jLabel_nama.setBounds(30, 180, 101, 45);

        btn_logout.setBackground(new java.awt.Color(227, 247, 255));
        btn_logout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        panel_menu.add(btn_logout);
        btn_logout.setBounds(80, 640, 200, 50);

        btn_caridata.setBackground(new java.awt.Color(227, 247, 255));
        btn_caridata.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_caridata.setText("CARI DATA");
        btn_caridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caridataActionPerformed(evt);
            }
        });
        panel_menu.add(btn_caridata);
        btn_caridata.setBounds(80, 400, 200, 50);

        btn_laporan.setBackground(new java.awt.Color(227, 247, 255));
        btn_laporan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_laporan.setText("LAPORAN");
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        panel_menu.add(btn_laporan);
        btn_laporan.setBounds(80, 560, 200, 50);

        btn_menuutama.setBackground(new java.awt.Color(227, 247, 255));
        btn_menuutama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_menuutama.setText("MENU UTAMA");
        btn_menuutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuutamaActionPerformed(evt);
            }
        });
        panel_menu.add(btn_menuutama);
        btn_menuutama.setBounds(80, 320, 200, 50);

        btn_input.setBackground(new java.awt.Color(227, 247, 255));
        btn_input.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        panel_menu.add(btn_input);
        btn_input.setBounds(80, 480, 200, 50);

        txt_Id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_Id);
        txt_Id.setBounds(160, 130, 180, 45);

        txt_Nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_Nama);
        txt_Nama.setBounds(160, 180, 180, 45);

        txt_Hp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_Hp);
        txt_Hp.setBounds(160, 230, 180, 45);

        jLabel6.setText("jLabel4");
        panel_menu.add(jLabel6);
        jLabel6.setBounds(180, 260, 51, 20);

        jLabel7.setText("jLabel7");
        panel_menu.add(jLabel7);
        jLabel7.setBounds(230, 200, 51, 20);

        jPanel1.add(panel_menu);
        panel_menu.setBounds(0, 2, 359, 720);

        panel_bground2.setBackground(new java.awt.Color(255, 255, 255));
        panel_bground2.setLayout(null);

        jLabel_namagalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_namagalonman.setText("NAMA GALONMAN :");
        panel_bground2.add(jLabel_namagalonman);
        jLabel_namagalonman.setBounds(40, 520, 228, 47);

        txt_namagalonman.setBackground(new java.awt.Color(196, 196, 196));
        txt_namagalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_bground2.add(txt_namagalonman);
        txt_namagalonman.setBounds(330, 520, 380, 40);

        txt_namapelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_namapelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_bground2.add(txt_namapelanggan);
        txt_namapelanggan.setBounds(330, 70, 377, 40);

        jLabel_namapelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_namapelanggan.setText("NAMA PELANGGAN :");
        panel_bground2.add(jLabel_namapelanggan);
        jLabel_namapelanggan.setBounds(40, 70, 228, 47);

        txt_alamat.setBackground(new java.awt.Color(196, 196, 196));
        txt_alamat.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_bground2.add(txt_alamat);
        txt_alamat.setBounds(330, 120, 377, 40);

        jLabel_alamat.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_alamat.setText("ALAMAT :");
        panel_bground2.add(jLabel_alamat);
        jLabel_alamat.setBounds(40, 120, 228, 47);

        txt_nohppelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_nohppelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_bground2.add(txt_nohppelanggan);
        txt_nohppelanggan.setBounds(330, 170, 377, 40);

        jLabel_nohppelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nohppelanggan.setText("NO HP :");
        panel_bground2.add(jLabel_nohppelanggan);
        jLabel_nohppelanggan.setBounds(40, 170, 228, 47);

        txt_pesanan.setBackground(new java.awt.Color(196, 196, 196));
        txt_pesanan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txt_pesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pesananKeyTyped(evt);
            }
        });
        panel_bground2.add(txt_pesanan);
        txt_pesanan.setBounds(330, 220, 377, 40);

        jLabel_pesanan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_pesanan.setText("PESANAN :");
        panel_bground2.add(jLabel_pesanan);
        jLabel_pesanan.setBounds(40, 220, 228, 47);

        jLabel_biaya.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_biaya.setText("BIAYA :");
        panel_bground2.add(jLabel_biaya);
        jLabel_biaya.setBounds(40, 320, 228, 47);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Total Biaya :");
        panel_bground2.add(jLabel3);
        jLabel3.setBounds(40, 370, 190, 29);

        txt_total.setBackground(new java.awt.Color(196, 196, 196));
        panel_bground2.add(txt_total);
        txt_total.setBounds(330, 370, 380, 40);

        cbo_idgalonman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_idgalonman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbo_idgalonmanMouseClicked(evt);
            }
        });
        cbo_idgalonman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_idgalonmanActionPerformed(evt);
            }
        });
        panel_bground2.add(cbo_idgalonman);
        cbo_idgalonman.setBounds(330, 470, 380, 40);

        jLabel_idgalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_idgalonman.setText("ID GALONMAN :");
        panel_bground2.add(jLabel_idgalonman);
        jLabel_idgalonman.setBounds(40, 470, 228, 47);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("VOUCHER :");
        panel_bground2.add(jLabel4);
        jLabel4.setBounds(40, 430, 200, 29);

        cbo_voucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Gelas", "Piring", "Kipas", "Sendok" }));
        panel_bground2.add(cbo_voucher);
        cbo_voucher.setBounds(330, 420, 380, 40);

        btn_batalkan.setBackground(new java.awt.Color(255, 0, 0));
        btn_batalkan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_batalkan.setText("BATALKAN");
        btn_batalkan.setBorder(null);
        btn_batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalkanActionPerformed(evt);
            }
        });
        panel_bground2.add(btn_batalkan);
        btn_batalkan.setBounds(130, 570, 200, 50);

        btn_kirim.setBackground(new java.awt.Color(0, 255, 25));
        btn_kirim.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_kirim.setText("KIRIM");
        btn_kirim.setBorder(null);
        btn_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimActionPerformed(evt);
            }
        });
        panel_bground2.add(btn_kirim);
        btn_kirim.setBounds(590, 570, 200, 50);

        jLabel_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_idpelanggan.setText("ID PELANGGAN :");
        panel_bground2.add(jLabel_idpelanggan);
        jLabel_idpelanggan.setBounds(40, 10, 228, 47);

        txt_idpelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_bground2.add(txt_idpelanggan);
        txt_idpelanggan.setBounds(330, 20, 377, 40);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setText("DISKON :");
        panel_bground2.add(jLabel5);
        jLabel5.setBounds(40, 280, 110, 29);

        txt_diskon.setBackground(new java.awt.Color(196, 196, 196));
        txt_diskon.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txt_diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diskonActionPerformed(evt);
            }
        });
        txt_diskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_diskonKeyPressed(evt);
            }
        });
        panel_bground2.add(txt_diskon);
        txt_diskon.setBounds(330, 270, 377, 40);

        txt_biaya.setBackground(new java.awt.Color(196, 196, 196));
        panel_bground2.add(txt_biaya);
        txt_biaya.setBounds(330, 320, 380, 40);

        jPanel1.add(panel_bground2);
        panel_bground2.setBounds(358, 104, 1082, 920);

        panel_galon.setMinimumSize(new java.awt.Dimension(893, 861));
        panel_galon.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GALON.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(893, 163));
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        panel_galon.add(jLabel2);
        jLabel2.setBounds(0, 0, 893, 861);

        jPanel1.add(panel_galon);
        panel_galon.setBounds(431, 163, 893, 861);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1302, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar ?", "LOGOUT", JOptionPane.YES_NO_OPTION);
            
        if(response == JOptionPane.YES_OPTION){
            Form_Login l = new Form_Login();
            if(getjLabel7().getText().equalsIgnoreCase("Tersedia")){
                l.getKeterangan().setText("Tersedia");
            }
            else
            {
                l.getKeterangan().setText("Tidak tersedia");
            }
            l.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalkanActionPerformed
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus ?", "DELETE", JOptionPane.YES_NO_OPTION);
            
        if(response == JOptionPane.YES_OPTION){
           controllerM.clearForm();
        }                                          
        else if(response==JOptionPane.NO_OPTION){
            // Isi fungsinya disini ...
        }
        
    }//GEN-LAST:event_btn_batalkanActionPerformed

    private void btn_caridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caridataActionPerformed
        // TODO add your handling code here:
        Form_Caridata f = new Form_Caridata();
            f.setVisible(true);
            f.toFront();
            f.getTxt_Id().setText(getTxt_Id().getText());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
            f.getjLabel3().setText(getjLabel6().getText());
            f.getjLabel4().setText(getjLabel7().getText());
            if(getjLabel7().getText().equalsIgnoreCase("Tersedia")){
                f.getBtn_input().setEnabled(true);
            }
            else
            {
                f.getBtn_input().setEnabled(false);
            }
            if(getjLabel6().getText().equalsIgnoreCase("Owner"))
            {
                f.getBtn_edit().setEnabled(true);
                f.getBtn_laporan().setEnabled(true);
            }
            else{
                f.getBtn_laporan().setEnabled(false);
                f.getBtn_edit().setEnabled(false);
            }
            dispose();
    }//GEN-LAST:event_btn_caridataActionPerformed

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed
        // TODO add your handling code here:
        controllerM.KirimP();
        controllerM.KirimM();
        controllerM.clearForm();
    }//GEN-LAST:event_btn_kirimActionPerformed

    private void txt_pesananKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesananKeyTyped
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(getTxt_pesanan().getText());
            int biaya = x*5000;
            getTxt_biaya().setText(biaya + "");
        }
        catch(NumberFormatException e){}
                
    }//GEN-LAST:event_txt_pesananKeyTyped

    private void btn_menuutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuutamaActionPerformed
        // TODO add your handling code here:
        Form_MenuUtama f = new Form_MenuUtama();
            f.setVisible(true);
            f.toFront();
            f.getTxt_Id().setText(getTxt_Id().getText());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
            f.getjLabel3().setText(getjLabel6().getText());
            f.getTxt_statusair().setText(getjLabel7().getText());
            if(getjLabel7().getText().equalsIgnoreCase("Tersedia")){
                f.getBtn_input().setEnabled(true);
            }
            else
            {
                f.getBtn_input().setEnabled(false);
            }
            if(getjLabel6().getText().equalsIgnoreCase("Owner"))
            {
                f.getBtn_laporan().setEnabled(true);
            }
            else{
                f.getBtn_laporan().setEnabled(false);
            }
            dispose();
    }//GEN-LAST:event_btn_menuutamaActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
//        Form_Input f = new Form_Input();
//            f.setVisible(true);
//            f.toFront();
//            f.getTxt_Id().setText(getTxt_Id().getText());
//            f.getTxt_Id().setEditable(false);
//            f.getTxt_Nama().setText(getTxt_Nama().getText());
//            f.getTxt_Nama().setEditable(false);
//            f.getTxt_Hp().setText(getTxt_Hp().getText());
//            f.getTxt_Hp().setEditable(false);
//            f.getjLabel6().setText(getjLabel6().getText());
//            f.getjLabel7().setText(getjLabel7().getText());
//            dispose();
    }//GEN-LAST:event_btn_inputActionPerformed

    private void txt_diskonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diskonKeyPressed
        try{
            int diskon = Integer.parseInt(getTxt_diskon().getText());
            int biaya = Integer.parseInt(getTxt_biaya().getText());
            int total = biaya-diskon;
            getTxt_total().setText(total + "");
        }
        catch(NumberFormatException e){}
    }//GEN-LAST:event_txt_diskonKeyPressed

    private void cbo_idgalonmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_idgalonmanMouseClicked
       String id= cbo_idgalonman.getSelectedItem().toString();
       if(id.equals("G001"))
       {
           txt_namagalonman.setText("Randi");
       }
       else
       {
           txt_namagalonman.setText("Dani");
       }
    }//GEN-LAST:event_cbo_idgalonmanMouseClicked

    private void txt_diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diskonActionPerformed

    private void cbo_idgalonmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_idgalonmanActionPerformed
       
    }//GEN-LAST:event_cbo_idgalonmanActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        Form_Laporan f= new Form_Laporan();
        f.setVisible(true);
        f.getjLabel4().setText(getjLabel6().getText());
        f.getjLabel2().setText(getjLabel7().getText());
       f.getTxt_Id().setText(getTxt_Id().getText());
       f.getTxt_Id().setEditable(false);
       f.getTxt_Nama().setText(getTxt_Nama().getText());
       f.getTxt_Nama().setEditable(false);
       f.getTxt_Hp().setText(getTxt_Hp().getText());
       f.getTxt_Hp().setEditable(false);
        dispose();
    }//GEN-LAST:event_btn_laporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batalkan;
    private javax.swing.JButton btn_caridata;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_kirim;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_menuutama;
    private javax.swing.JComboBox<String> cbo_idgalonman;
    private javax.swing.JComboBox<String> cbo_voucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_alamat;
    private javax.swing.JLabel jLabel_biaya;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_idgalonman;
    private javax.swing.JLabel jLabel_idpelanggan;
    private javax.swing.JLabel jLabel_nama;
    private javax.swing.JLabel jLabel_namagalonman;
    private javax.swing.JLabel jLabel_namapelanggan;
    private javax.swing.JLabel jLabel_nohp;
    private javax.swing.JLabel jLabel_nohppelanggan;
    private javax.swing.JLabel jLabel_pesanan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_bground2;
    private javax.swing.JPanel panel_galon;
    private javax.swing.JPanel panel_judul;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JTextField txt_Hp;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_biaya;
    private javax.swing.JTextField txt_diskon;
    private javax.swing.JTextField txt_idpelanggan;
    private javax.swing.JTextField txt_namagalonman;
    private javax.swing.JTextField txt_namapelanggan;
    private javax.swing.JTextField txt_nohppelanggan;
    private javax.swing.JTextField txt_pesanan;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
