/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import ExportExcel.FormExport;
import Koneksi.Koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author USER
 */
public class Form_Laporan extends javax.swing.JFrame {


    /**
     * Creates new form Form_MenuUtama
     */
    public Form_Laporan() {
        initComponents();
        //panel_galon.setBackground(new Color(225,225,225,255));
        paneljudul_table.setBackground(new Color(229,229,229,242));
        tableMemesan();
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }
    public javax.swing.JTextField getTxt_Id(){
        return txt_Id;
    }
    
    public javax.swing.JTextField getTxt_Nama(){
        return txt_Nama;
    }
    
    public javax.swing.JTextField getTxt_Hp(){
        return txt_Hp;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }
    
     private void tableMemesan(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No pesanan");
        model.addColumn("Id Pelanggan");
        model.addColumn("Id Karyawan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Jumlah Pesanan");
        model.addColumn("Vourcher");
        model.addColumn("Tgl Pesanan");
        model.addColumn("Biaya");
        try{
            Koneksi k = new Koneksi();
            Connection con = k.getKoneksi();
            String sql = "SELECT memesan.nopesanan, memesan.id_p, memesan.id_k, "
                    + "pelanggan.nama_p, memesan.jmlpesanan, memesan.voucher, memesan.tglpesanan, "
                    + "memesan.biaya FROM memesan memesan INNER JOIN pelanggan "
                    + "pelanggan ON memesan.id_p=pelanggan.id_p "
                    + "ORDER BY memesan.tglpesanan DESC;";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()){
                model.addRow(new Object[] {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8)
                });
            }
            table2.setModel(model);
        } catch(Exception e){
            System.out.println("Error => "+e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_batalkan = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        table = new javax.swing.JTable();
        paneljudul_table = new javax.swing.JPanel();
        judultable_idpelanggan = new javax.swing.JLabel();
        judultable_idkaryawan = new javax.swing.JLabel();
        judultable_idk_antar = new javax.swing.JLabel();
        judultable_nama = new javax.swing.JLabel();
        judultable_jml = new javax.swing.JLabel();
        judultable_diskon = new javax.swing.JLabel();
        judultable_voucher = new javax.swing.JLabel();
        judultable_tglpesanan = new javax.swing.JLabel();
        judultable_jmlpembayaran = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        txt_Nama = new javax.swing.JTextField();
        txt_Hp = new javax.swing.JTextField();
        panel_galon = new javax.swing.JPanel();
        gambar_galon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        panel_judul.setPreferredSize(new java.awt.Dimension(1440, 115));
        panel_judul.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN");
        panel_judul.add(jLabel1);
        jLabel1.setBounds(300, 20, 679, 60);

        jLabel3.setText("jLabel4");
        panel_judul.add(jLabel3);
        jLabel3.setBounds(30, 280, 41, 16);

        jPanel1.add(panel_judul);
        panel_judul.setBounds(0, 0, 1478, 140);

        btn_batalkan.setBackground(new java.awt.Color(48, 179, 235));
        btn_batalkan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_batalkan.setText("Home");
        btn_batalkan.setBorder(null);
        btn_batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalkanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batalkan);
        btn_batalkan.setBounds(70, 590, 200, 50);

        btn_cetak.setBackground(new java.awt.Color(48, 179, 235));
        btn_cetak.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_cetak.setText("CETAK LAPORAN");
        btn_cetak.setBorder(null);
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak);
        btn_cetak.setBounds(950, 580, 200, 50);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 1260, 90);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "ID Karyawan", "ID K.Antar", "Nama Pelanggan", "Jumlah Pesanan", "Diskon", "Voucher", "Tanggal Pesanan", "Jumlah Pembayaran"
            }
        ));
        table.setGridColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(table);
        table.setBounds(10, 270, 1260, 210);

        paneljudul_table.setBackground(new java.awt.Color(229, 229, 229));
        paneljudul_table.setLayout(null);

        judultable_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idpelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idpelanggan.setText("ID Pelanggan");
        judultable_idpelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneljudul_table.add(judultable_idpelanggan);
        judultable_idpelanggan.setBounds(0, 0, 140, 50);

        judultable_idkaryawan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idkaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idkaryawan.setText("ID Karyawan");
        judultable_idkaryawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneljudul_table.add(judultable_idkaryawan);
        judultable_idkaryawan.setBounds(140, 0, 140, 50);

        judultable_idk_antar.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idk_antar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idk_antar.setText("ID K.Antar");
        judultable_idk_antar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneljudul_table.add(judultable_idk_antar);
        judultable_idk_antar.setBounds(280, 0, 140, 50);

        judultable_nama.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_nama.setText("Nama Pelanggan");
        judultable_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneljudul_table.add(judultable_nama);
        judultable_nama.setBounds(420, 0, 140, 50);

        judultable_jml.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_jml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_jml.setText("Jumlah Pesanan");
        judultable_jml.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneljudul_table.add(judultable_jml);
        judultable_jml.setBounds(560, 0, 140, 50);

        judultable_diskon.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_diskon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_diskon.setText("Diskon");
        judultable_diskon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneljudul_table.add(judultable_diskon);
        judultable_diskon.setBounds(700, 0, 140, 50);

        judultable_voucher.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_voucher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_voucher.setText("Voucher");
        judultable_voucher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneljudul_table.add(judultable_voucher);
        judultable_voucher.setBounds(840, 0, 140, 50);

        judultable_tglpesanan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_tglpesanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_tglpesanan.setText("Tanggal Pesanan");
        judultable_tglpesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneljudul_table.add(judultable_tglpesanan);
        judultable_tglpesanan.setBounds(980, 0, 140, 50);

        judultable_jmlpembayaran.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_jmlpembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_jmlpembayaran.setText("Jumlah Pembayaran");
        judultable_jmlpembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        judultable_jmlpembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        judultable_jmlpembayaran.setFocusable(false);
        paneljudul_table.add(judultable_jmlpembayaran);
        judultable_jmlpembayaran.setBounds(1120, 0, 140, 50);

        jPanel1.add(paneljudul_table);
        paneljudul_table.setBounds(10, 220, 1260, 50);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 40, 41, 16);

        txt_Id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_Id);
        txt_Id.setBounds(0, 0, 180, 45);

        txt_Nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_Nama);
        txt_Nama.setBounds(0, 40, 180, 45);

        txt_Hp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_Hp);
        txt_Hp.setBounds(0, 90, 180, 45);

        panel_galon.setMinimumSize(new java.awt.Dimension(893, 861));
        panel_galon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_galonAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panel_galon.setLayout(null);

        gambar_galon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GALON.jpg"))); // NOI18N
        gambar_galon.setPreferredSize(new java.awt.Dimension(893, 163));
        gambar_galon.setRequestFocusEnabled(false);
        gambar_galon.setVerifyInputWhenFocusTarget(false);
        panel_galon.add(gambar_galon);
        gambar_galon.setBounds(0, 0, 893, 861);

        jLabel4.setText("jLabel4");
        panel_galon.add(jLabel4);
        jLabel4.setBounds(50, 40, 41, 16);

        jPanel1.add(panel_galon);
        panel_galon.setBounds(274, 114, 893, 861);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1302, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_galonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_galonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_galonAncestorAdded

    private void btn_batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalkanActionPerformed
        Form_MenuUtama f = new Form_MenuUtama();
            f.setVisible(true);
            f.toFront();
            f.getTxt_Id().setText(getTxt_Id().getText());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
            f.getjLabel3().setText(getjLabel4().getText());
            f.getTxt_statusair().setText(getjLabel2().getText());
            if(getjLabel2().getText().equalsIgnoreCase("Tersedia")){
                f.getBtn_input().setEnabled(true);
            }
            else
            {
                f.getBtn_input().setEnabled(false);
            }
            dispose();
    }//GEN-LAST:event_btn_batalkanActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        FormExport f = new FormExport();
        f.setVisible(true);
        f.getTxt_Id().setText(getTxt_Id().getText());
        f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
            f.getjLabel6().setText(getjLabel4().getText());
            f.getjLabel7().setText(getjLabel2().getText());
        dispose();
    }//GEN-LAST:event_btn_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Laporan().setVisible(true);
                
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batalkan;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JLabel gambar_galon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judultable_diskon;
    private javax.swing.JLabel judultable_idk_antar;
    private javax.swing.JLabel judultable_idkaryawan;
    private javax.swing.JLabel judultable_idpelanggan;
    private javax.swing.JLabel judultable_jml;
    private javax.swing.JLabel judultable_jmlpembayaran;
    private javax.swing.JLabel judultable_nama;
    private javax.swing.JLabel judultable_tglpesanan;
    private javax.swing.JLabel judultable_voucher;
    private javax.swing.JPanel panel_galon;
    private javax.swing.JPanel panel_judul;
    private javax.swing.JPanel paneljudul_table;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JTextField txt_Hp;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Nama;
    // End of variables declaration//GEN-END:variables
}
